### ISSUE TITLE
Client should provide its own hostname instead of relying on DNS

### ISSUE THREAD

**Issue by phckopper** [pedrorigon/wakeUP_Computer#4]
Currently, hostnames are being queried over DNS everytime a client goes online. This is suboptimal as most home networks do not provide reverse DNS lookups. We should switch to providing hostnames inside our discovery payloads instead.

https://github.com/pedrorigon/wakeUP_Computer/blob/345abc11e370af95beb42653369bba164dd60115/discovery_service.c#L26

https://github.com/pedrorigon/wakeUP_Computer/blob/345abc11e370af95beb42653369bba164dd60115/discovery_service.c#L125

**Comment by phckopper** [comment]
Might be blocked by #2 as we'll be changing our way of sending packages

**Comment by nikname22** [comment]
No more needed.
